### ISSUE TITLE
Getting "There are no dependencies!" with `cost-of-modules --no-install`

### ISSUE THREAD

**Issue by kentcdodds** [siddharthkp/cost-of-modules#10]
This is odd, but I wonder if it's because [my project](https://github.com/javascriptair/site) has no production dependencies (only dev). There are definitely modules in `node_modules` though. Any ideas?

**Comment by siddharthkp** [comment]
Yep, it only checks prod dependencies because those are the ones that get distributed

If you're looking for optimising dev depencies as well, I can include another flag `cost-of-modules --include-dev`

**Comment by kentcdodds** [comment]
Gotcha, makes total sense. Yeah, I'd love a `--include-dev` if you feel so inclined :)

**Comment by siddharthkp** [comment]
@kentcdodds Published in `0.3.0`!
