### ISSUE TITLE
feature: devDeps listed as deps

### ISSUE THREAD

**Issue by jonschlinkert** [siddharthkp/cost-of-modules#14]
You have this listed on your todo list: "Check if there are any dev dependencies that are specified as dependencies (tricky)"

I have a package, [lint-deps](https://github.com/jonschlinkert/lint-deps) that would be able to do this once I get the refactor pushed up (it's finished but I need to do unit tests). As it is currently, lint-deps is really geared around CLI usage, but the refactor will make it easier to use via API, so you would be able to run it on each package in the dependency tree to get a report back. 

just a thought, in case you're interested in this (fwiw, after using lint-deps for a while I've found that libs have unused deps way more often than I would have thought)

**Comment by siddharthkp** [comment]
@jonschlinkert This is really helpful, thanks!

**Comment by siddharthkp** [comment]
Closing this for now, will pick it up when I have a chunk of time 😄
