### ISSUE TITLE
Private repos have `NaNM` size

### ISSUE THREAD

**Issue by phil-r** [siddharthkp/cost-of-modules#15]
Hi, I've tried to run `cost-of-modules` on our company project and our private dependency size was counted as `NaNM`
![image](https://cloud.githubusercontent.com/assets/577316/19851101/8096f096-9f5c-11e6-96a1-a545186723db.png)

**Comment by siddharthkp** [comment]
@phil-r This is tricky to debug, I don't have any private npm packages to test this with.

Can you give me the output of this - 
`du -d 1 -k node_modules`

We [can DM](https://github.com/siddharthkp) if you would prefer that.

**Comment by siddharthkp** [comment]
@phil-r Published 0.3.2!

**Comment by siddharthkp** [comment]
@phil-r This problem might not be fully solved. Can you pass me the folder structure inside your private repo
