### ISSUE TITLE
Show module sizes for browserified bundles?

### ISSUE THREAD

**Issue by fergiemcdowall** [siddharthkp/cost-of-modules#25]
It would be so good if this lib could show sizes of modules in browserify bundles. (or maybe it can already- if so how..?)

**Comment by siddharthkp** [comment]
I think what you're looking for is [source-map-explorer](https://github.com/danvk/source-map-explorer) by @danvk

It's really good. 

Bonus: [Totally Tooling Tips](https://www.youtube.com/watch?v=7aY9BoMEpG8) episode on the same.
