### ISSUE TITLE
Feature: Read bower dependencies

### ISSUE THREAD

**Issue by dphochman** [siddharthkp/cost-of-modules#29]
In my app (based on angular-seed), the runtime dependencies are installed by `bower install` which is triggered by npm script `postinstall`, and not detected by cost-of-modules.  `bower.json` declares the runtime dependencies, and `.bowerrc` declares the directory where the dependencies are installed (the default directory is `bower_components/`).  

I realize that this request may lead to a vortex of unreachable goals, such as a deep understanding of the impact of specific npm scripts, obscure options in bower, or supporting other package managers.  Perhaps each of those can be prioritized and tackled independently.  AFAIK, using bower for runtime dependencies is a popular practice.

**Comment by siddharthkp** [comment]
Can't deny that bower is still pretty popular. But, that sounds like another project of it's own. Wouldn't want to add that to this repo.

**Comment by dphochman** [comment]
Of course, you are correct.  Small pieces loosely joined...

If it's OK with you to fork or require "cost-of-modules" to jumpstart a "cost-of-packages" or "cost-of-bower" package, that's the route I'll pursue.  If it works, I may attempt to register it on bower.io.  And that may lead me or others to enter the above-mentioned vortex. 

Thank you for this work.

**Comment by siddharthkp** [comment]
@dphochman Of course! Go for it!
