### ISSUE TITLE
Tests fail on master

### ISSUE THREAD

**Issue by brekk** [siddharthkp/cost-of-modules#33]
Hi there,

Excited to be integrating this tool, so thank you for your work. I found while playing out with a clone of this repo that `npm test` results in two failing tests on `master`, without my having written any new code.

```
   1. 0prod › get size for node_modules
   [ { name: '@whitneyit/data-fn', size: 7 },
  { name: 'date-time', size: 4 },
  { name: 'is', size: 56 },
  { name: 'node.extend' === [ { name: '@whitneyit/data-fn', size: 7 },
  { name: 'date-time', size: 4 },
  { name: 'is', size: 55 },
  { name: 'node.extend'
      { name: 'node.extend'
        Test.fn (fixtures/tests.js:41:11)
        _combinedTickCallback (internal/process/next_tick.js:67:7)
        process._tickCallback (internal/process/next_tick.js:98:9)


   2. 1dev › get size for node_modules
   [ { name: '@whitneyit/data-fn', size: 7 },
  { name: 'camelcase', size: 5 },
  { name: 'date-time', size: 4 },
  { name: 'is', s === [ { name: '@whitneyit/data-fn', size: 7 },
  { name: 'camelcase', size: 5 },
  { name: 'date-time', size: 4 },
  { name: 'is', s
      { name: 'is', s
        Test.fn (fixtures/tests.js:41:11)
        _combinedTickCallback (internal/process/next_tick.js:67:7)
        process._tickCallback (internal/process/next_tick.js:98:9)
```

This makes it hard to know where to start when contributing.

Thanks for your work and your time!

*Edit*: Running on El Capitan OSX 10.11.6 and `node v.6.2.1`, was also able to reproduce on my work machine, which has similar specs.

--
Brekk

**Comment by siddharthkp** [comment]
Ouch! 

I can't get to a machine right now 🏄
Will get to it on wednesday 

P.S. thanks for the kind words!

**Comment by siddharthkp** [comment]
Fixed in https://github.com/siddharthkp/cost-of-modules/pull/34

**Comment by siddharthkp** [comment]
@brekk The tests structure is a bit weird, let me know if you need any help. (I plan/hope to clean it up soon)
