### ISSUE TITLE
Running this removes dev modules

### ISSUE THREAD

**Issue by ffxsam** [siddharthkp/cost-of-modules#35]
Is it normal for this script to blow away dev dependencies? I think when it runs `npm install --production`, for some reason, any dev dependencies in `node_modules` are gone.

**Comment by siddharthkp** [comment]
Yes, `--production` does that. Do you think it would be a good idea to reinstall them after running the command?

**Comment by ffxsam** [comment]
I think it would be an even better idea to not run `npm install --production`. I always know that my packages are installed and up to date before I run `cost-of-modules`. And then maybe provide an option, e.g. `cost-of-modules -i` to ensure packages are installed.

**Comment by ffxsam** [comment]
Ah I see. Never mind then, best to leave it as is and not automatically reinstall after.

**Comment by alshakero** [comment]
@siddharthkp maybe rename the original node_modules to something and then restore it when done measuring?

**Comment by siddharthkp** [comment]
@alshakero I was thinking the same. Will implement it today

**Comment by siddharthkp** [comment]
@alshakero Code review please https://github.com/siddharthkp/cost-of-modules/pull/36

**Comment by siddharthkp** [comment]
Update: I couldn't reproduce the bug! 😳

@ffxsam `npm install --production` does not remove devDependencies for me. Which version of npm are you on?

**Comment by alshakero** [comment]
@siddharthkp done.

**Comment by siddharthkp** [comment]
@ffxsam published, just update cost-of-modules 😄

**Comment by ffxsam** [comment]
It does remove the devDependencies as far as I can tell:

```
$ ls -l node_modules | wc -l
     851
$ npm i --production
[output removed - a very long list of dev packages]
$ ls -l node_modules | wc -l
     465
```

And then when I run my app, there are errors because of missing dev dependencies.

I'm using npm 4.4.4 and node 6.10.1.

**Comment by siddharthkp** [comment]
@ffxsam, is that with cost-of-modules@1.0.0?

**Comment by ffxsam** [comment]
@siddharthkp nope, this was 0.5.2. I was just telling you because you said that for you, it wasn't deleting dev dependencies.

But that's irrelevant now that the new version is out I suppose. 😄  I'll grab it and give it a shot.

**Comment by ffxsam** [comment]
Works great!

**Comment by siddharthkp** [comment]
🎉 

Thanks for reporting it.
