### ISSUE TITLE
TypeError: Buffer.alloc is not a function

### ISSUE THREAD

**Issue by umarashfaq** [siddharthkp/cost-of-modules#41]
Ran `cost-of-modules` in a node project directory. Got this error:

<img width="970" alt="screen shot 2017-05-28 at 3 48 21 pm" src="https://cloud.githubusercontent.com/assets/1681120/26528128/29e02f46-43bd-11e7-91fb-3dcdacb4338e.png">

**Comment by alshakero** [comment]
Hi! Nice name 😆 

Could you please show me the output of:
```sh
node -v
```

**Comment by umarashfaq** [comment]
:D

`4.3.2`

**Comment by alshakero** [comment]
`Buffer` is only available after Node 5.0.0. And[ this lib supports Node >= 5.0.0](https://github.com/siddharthkp/cost-of-modules/blob/master/package.json#L23)

**Comment by umarashfaq** [comment]
I see, thanks for your prompt response.

**Comment by siddharthkp** [comment]
thanks @alshakero!

side thought: should we add a warning for unsupported node versions instead of just crashing?

In my head, it's a npm package that can be imported and decides based on `engine` in package.json
