### ISSUE TITLE
Size of the entire package

### ISSUE THREAD

**Issue by kof** [siddharthkp/cost-of-modules#6]
I have just tried and it seems it prints out the size of the entire package, which is not very usefull, as not everything from a package is really used.

Could we add information of sizes from ever package which really end up in the build?

**Comment by siddharthkp** [comment]
@kof Hey, it takes the `node_modules` that are `dependencies`, these are the ones that will get will get distributed as well.
What the tool doesn't do right now is add up files from the package itself that will get published.

**Comment by kof** [comment]
Sure, however if I install lodash package, doesn't mean I use the entire lodash library, so its not usefull to know the size of lodash.

**Comment by siddharthkp** [comment]
I see, are you talking about bundling parts of the dependencies in a bundle. Correct me, if I'm wrong, you will not put those in your module's `dependencies` in `package.json`

I feel I'm not understanding your question.

P.S. These might help if that's the case.
I think what you're looking for is [webpack-bundle-size-analyzer](https://github.com/robertknight/webpack-bundle-size-analyzer) or [source-map-explorer](https://github.com/danvk/source-map-explorer) (browserify)

**Comment by kof** [comment]
yeah, I am talking about code that adds up to the size of the final application. I am not even sure this project is the right place to track such stuff. However I think this is the only information that actually really matters.

**Comment by siddharthkp** [comment]
I need to understand this better, DM on twitter?

**Comment by kof** [comment]
sure, but I think you pointer already to the right solution, which is the webpack bundle size analyzer in my case. I was just under impression initially cost-of-modules will give me exactly this.

**Comment by siddharthkp** [comment]
I'd still like to pick your brain, if that's alright 😄

**Comment by kof** [comment]
sure)))
