### ISSUE TITLE
Add flag to not run install script

### ISSUE THREAD

**Issue by kentcdodds** [siddharthkp/cost-of-modules#7]
I use `yarn` to install my packages and having `cost-of-modules` run `npm install --production` is kind of annoying. I'd like to be able to say: `cost-of-modules --no-install` to skip that part.

**Comment by siddharthkp** [comment]
@kentcdodds Hey would it make sense to use yarn instead? 

`cost-of-modules --yarn` which will run `yarn install --produciton`

**Comment by kentcdodds** [comment]
That would be great in addition. But I'd actually prefer the default to not do any installation. I'd prefer to do the installation myself before running the script.

**Comment by siddharthkp** [comment]
@kentcdodds Released in `0.2.6`

`cost-of-modules --no-install`
